SET serveroutput ON;
 
CREATE TABLE users (
    id NUMBER(12) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    nickname VARCHAR2(15) NOT NULL UNIQUE,
    email VARCHAR2(30) NOT NULL UNIQUE,
    passwd VARCHAR2(10),
    admin NUMBER(1) NOT NULL,
    contests VARCHAR2(20),
    CONSTRAINT check_adm
    CHECK (admin=1 OR admin=0)
);

ALTER TABLE users ADD (CONSTRAINT user_pk PRIMARY KEY(id));
 
CREATE TABLE contests (
    id NUMBER(12) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    title VARCHAR2(20) NOT NULL,
    description nclob,
    rating NUMBER,
    finished NUMBER(1) NOT NULL,
    CONSTRAINT check_finished
    CHECK (finished=1 OR finished=0)
);

ALTER TABLE contests ADD (CONSTRAINT contest_pk PRIMARY KEY(id));
 
CREATE TABLE films (
    id NUMBER(12) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    title VARCHAR2(30) NOT NULL,
    YEAR NUMBER(4)
);

ALTER TABLE films ADD (CONSTRAINT film_pk PRIMARY KEY(id));
 
CREATE TABLE languages (
    id NUMBER(12) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    lang VARCHAR2(20) NOT NULL UNIQUE
);

ALTER TABLE languages ADD (CONSTRAINT lang_pk PRIMARY KEY(id));
 
CREATE TABLE genres (
    id NUMBER(12) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    name VARCHAR2(20) NOT NULL UNIQUE,
    description nclob
);

ALTER TABLE genres ADD (CONSTRAINT genre_pk PRIMARY KEY(id));

CREATE TABLE singers (
    id NUMBER(12) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    name VARCHAR2(20) NOT NULL UNIQUE,
    description nclob,
    languageID NUMBER(12)
);

ALTER TABLE singers ADD (CONSTRAINT singer_pk PRIMARY KEY(id));
ALTER TABLE singers ADD FOREIGN KEY (languageID) REFERENCES languages(id);

