CREATE OR REPLACE TRIGGER CHECK_DATE_IN_ALBUMS
	BEFORE INSERT OR UPDATE ON Albums FOR EACH ROW
	DECLARE
		OUT_OF_DATE_EXCEPTION EXCEPTION;
		PRAGMA EXCEPTION_INIT(OUT_OF_DATE_EXCEPTION, -20001);


BEGIN
	IF (:new.year > EXTRACT (YEAR FROM SYSDATE))
		THEN
			RAISE_APPLICATION_ERROR (-20101, 'Release year must be less than current date');
	END IF;
END;
/
